### ISSUE TITLE
Fix MD files

### ISSUE THREAD

**Issue by MarcBruins** [MvvmCross/mvvmcross-docs#3] opened 2017-03-22 12:17 UTC
The MD files contain weird/wrong characters right now. We should remove/replace those characters where needed. 

Example: `https://mvvmcross.github.io/mvvmcross-docs/documentation/tutorial/a-xamarinandroid-ui-project/a-xamarinandroid-ui-project.html`

**Comment by spockfish** [comment] 2017-03-27 15:22
It's not about characters. This is caused by specific Readme.io extensions (like tables) that has been used in the past. This needs to be changed manually I'm afraid. Can we for now make a list of all pages where these things occur so we can track down which are fixed and which not?

mvvmcross-docs/docs/_documentation/contribute/acknowledgements.md

**Comment by Cheesebaron** [comment] 2017-03-27 15:27
https://github.com/MvvmCross/mvvmcross-docs/search?utf8=%E2%9C%93&q=%5Bblock%3Aparameters%5D&type=

This should give you the idea of places

**Comment by MarcBruins** [comment] 2017-04-18 19:17
What is the progress on this @spockfish? I know there been done a lot but what is still open?

**Comment by spockfish** [comment] 2017-04-19 08:55
There's one thing at least on my list: proper indentation for the XML snippets. There's still some XML left where indentation is wrong.

I've created a script that extracts the XML, formats it, and put it back, but xmllint expects valid XML (seems reasonable). And that won't work because in most cases we're talking literally about snippets which aren't valid XML.

I think for now you can close this ticket.

**Closed** 2017-04-19 09:39 UTC
